<?php

namespace User\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAllUser()
    {

        return $this->createQueryBuilder('user')->select('count(user.id)')
        

                ->getQuery()->getSingleScalarResult();
       
    }
    
}
