user_index:
    path:     /user
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE
