<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{


    public function countAllCommande()
    {

        return $this->createQueryBuilder('commande')->select('count(commande.id)')
        

                ->getQuery()->getSingleScalarResult();
       
    }
    public function getAllCommandeJoinwithProduct()
      {
            return $this->createQueryBuilder('commande')
                  ->leftJoin('commande.produits','commande_produit')
                  ->addSelect('commande_produit')

                  ->leftJoin('commande_produit.commandes', 'produit')
                  ->addSelect('produit')

                  ->getQuery()
                  ->getResult();
      }
}
