<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

//Requete retournant le nombre de produit de la base de données
    public function countAllproduit()
    {

        return $this->createQueryBuilder('produit')->select('count(produit.id)')
        

                ->getQuery()->getSingleScalarResult();
       
    }


//Requete retournant les 3 derniers ajouts de produits de la base de données
    public function getAllproduit()
    {

        return $this->createQueryBuilder('produit')->select('produit')->orderBy('produit.id', 'DESC')->setMaxResults(3)
        

                ->getQuery()->getresult();
       
    }
    
}