app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /
admin:
    resource: '@AppBundle/Resources/config/routing/admin.yml'
    prefix: /admin
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /admin/produits

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user