user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /home

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user