app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /
admin:
    resource: '@AppBundle/Resources/config/routing/admin.yml'
    prefix: /admin
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /admin/produits

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

my_route_contact:
    path:  /contact
    defaults:  { _controller: AppBundle:App:contactForm }
    methods: POST
    options:
        expose: true