app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
app_produit:
    resource: "@AppBundle/Resources/config/routing/produit.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user