services:
#    user.example:
#        class: User\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
AppBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']
  _defaults:
    autowire: true
    autoconfigure: true
    public: false